resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [nodes:children]
    managers
    workers

    [managers:children]
    active
    standby

    [active]
    node001.netology.yc ansible_host=${yandex_compute_instance.node001.network_interface.0.nat_ip_address}

    [standby]
    node002.netology.yc ansible_host=${yandex_compute_instance.node002.network_interface.0.nat_ip_address}
    node003.netology.yc ansible_host=${yandex_compute_instance.node003.network_interface.0.nat_ip_address}

    [workers]
    node004.netology.yc ansible_host=${yandex_compute_instance.node004.network_interface.0.nat_ip_address}
    node005.netology.yc ansible_host=${yandex_compute_instance.node005.network_interface.0.nat_ip_address}
    node006.netology.yc ansible_host=${yandex_compute_instance.node006.network_interface.0.nat_ip_address}
    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.node001,
    yandex_compute_instance.node002,
    yandex_compute_instance.node003,
    yandex_compute_instance.node004,
    yandex_compute_instance.node005,
    yandex_compute_instance.node006
  ]
}
